Music_sharing_portal/urls.py
from django.contrib import admin
from django.urls import path,include

# register and login  routes registration
# importing from Users
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('music_app.urls')),
    path('register/',user_views.Register,name="Register"),
    path('user/login/',user_views.login,name="Login"),
    path('user/logout/',user_views.Logout,name="Logout"),
    path('user/account/',user_views.Profile,name="Account"),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=staticfiles_urlpatterns()

music_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.homepage,name="HomePage"),
    path('about/',views.aboutpage,name="AboutPage"),
    path('upload/',views.uploadMusic,name="UploadMusic"),
]

Users/models.py
from django.db import models

# Create your models here.

music_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
# class User(AbstractUser):
    # email=models.EmailField(unique=True)

class MusicFile(models.Model):
    PUBLIC = 'public'
    PRIVATE = 'private'
    PROTECTED = 'protected'
    
    VISIBILITY_CHOICES = [
        (PUBLIC, 'Public'),
        (PRIVATE, 'Private'),
        (PROTECTED, 'Protected'),
    ]
    title=models.CharField(max_length=100)
    music_file=models.FileField(upload_to='music/')
    visibility = models.CharField(max_length=10, choices=VISIBILITY_CHOICES, default=PUBLIC)
    allowed_users = models.ManyToManyField(User, related_name='allowed_files', blank=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted=models.DateTimeField(default=timezone.now)

Users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# in order to added extra email fields and to keep the configuration one place
class UserRegisterForm(UserCreationForm):
    email=forms.EmailField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class':'form-control'}),
    )
    class Meta:
        model=User
        fields=['username','email','password1']

Users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,login as user_login,authenticate


import re

def split_error_message(error_message):
    error_text = re.findall(r'<li>(.*?)</li>', error_message)
    return error_text

# REGISTER METHOD
def Register(request):
    
    if request.user.is_authenticated:
        return redirect("HomePage")
    if request.method == 'POST':
        form=UserRegisterForm(request.POST)
        
        if form.is_valid():
            username=form.cleaned_data.get('username')
            email=form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                messages.error(request,f"email already exists!")
                return redirect("Register")

            form.save()
            messages.success(request,f"Account Created has been created!You are now able to Login")
            return redirect("Login")
        else:
            error_message=str(form.errors)
            error_text=split_error_message(error_message)
            
            for error in error_text:
                error=error.split("<ul class=\"errorlist\"><li>")
                messages.error(request,f"{error[0]} : {error[1] } ")

    else:
        form=UserRegisterForm()    
    context={
        'title':'Register',
        'form':form,
    }
    return render(request,'Users/Register.html',context)



def login(request):
    
    if request.user.is_authenticated:
        return redirect("HomePage")

    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        user=User.objects.filter(email=email).first()
        if user is None:
            messages.error(request,f"User not exist.!")
            return redirect("Login")
        user = authenticate(request, email=email, password=password)
        # user=authenticate(username=user.username,password=password)
        if user is not None:
            if user.is_active:
                user_login(request,user)
                messages.success(request,f"You LogIn successfully.!")
                return redirect("HomePage")
            else:
                messages.error(request,f"disabled account")
        
        else:
            messages.error(request,f"Email or password incorrect.!")

    context={
        'title':'login',
    }

    return render(request,'Users/Login.html',context)

# ACCOUNT METHOD
@login_required
def Profile(request):
    context={
        'title':'Account',
    }
    return render(request,'Users/User.html',context)


#LOGOUT 
def Logout(request):
    logout(request)
    messages.success(request,f"User Logout Successfully!")
    return redirect("Login")

music_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import MusicFile
from django.db import models

# views here.
@login_required
def homepage(request):
    user=request.user
    
    #all music files uploaded by logged-user
    User_upload_files=MusicFile.objects.filter(
        models.Q(visibility=MusicFile.PUBLIC,uploaded_by=user)|
        models.Q(visibility=MusicFile.PRIVATE,uploaded_by=user)|
        models.Q(visibility=MusicFile.PROTECTED,uploaded_by=user)
    ).order_by('-date_posted')
    
    # GETTING THE ALL PUBLIC MUSIC FILES
    public_files=MusicFile.objects.filter(
        models.Q(visibility=MusicFile.PUBLIC)
    ).order_by('-date_posted')

    protected_files=MusicFile.objects.filter(
        models.Q(visibility=MusicFile.PROTECTED,allowed_users=user)
    ).order_by('-date_posted')

    #to get all music files containing the private,public,protected of user
    # music_files=MusicFile.objects.filter(
    #     models.Q(visibility=MusicFile.PUBLIC)|
    #     models.Q(visibility=MusicFile.PRIVATE,uploaded_by=user)|
    #     models.Q(visibility=MusicFile.PROTECTED,allowed_users=user)
    #     )
    
    context={
        'title':'HomePage',
        'public_files':public_files,
        'User_upload_files':User_upload_files,
        'protected_files':protected_files,
    }

    return render(request,'music-app/HomePage.html',context)


# ABOUT PAGE FUNCTION
def aboutpage(request):
    context={
        'title':'AboutPage'
    }
    return render(request,"music-app/AboutPage.html",context)

# UPLOADMUSIC METHOD
@login_required
def uploadMusic(request):
    if request.method=="POST":
        user=request.user
        title = request.POST['title']
        music_file = request.FILES.get('file')
        visibility = request.POST.get('visibility')
        print(visibility)
        musicFile = MusicFile(title=title, music_file=music_file, visibility=visibility, uploaded_by=user)
        musicFile.save()
        if visibility == MusicFile.PROTECTED:
            allowed_emails = request.POST.get('allowed_emails', '').split(',')
            allowed_users=User.objects.filter(email__in=allowed_emails)
            print(allowed_users)
            musicFile.allowed_users.set(allowed_users)

        messages.success(request,f"Music file Uploaded Successfully.!")
        return redirect("HomePage")
        
    context={
        'title':'Upload'
    }
    return render(request,"music-app/UploadMusic.html",context)

Users/templates/Users/Login.html
{% extends 'music-app/index.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'Users/index.css' %}">
{% endblock %}
{% block content %}
    <div class="forms">
    <div class="forms-container">
        <form class='fm-pg' method="POST"  >
            {% csrf_token %}
            <h3 class='fm-header'>Login</h3>
            <div className='fm-form'>
                <div>
                    <label for="email">Email:</label>
                    <input type="email" name="email" id="email">
                </div>

                <div>
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password">
                </div>
            </div>
            <button type="submit">Sign Up</button>
    </div>
    <div class="forms-container">
        <small class="text-muted">
            Don't have an Account?<a href="{% url 'Register' %}">Sign Up</a>
        </small>
    </div>
    </div>
{% endblock content %}



{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}

Users/templates/Users/Register.html
{% extends 'music-app/index.html' %}
{% load static %}
<!-- {% load crispy_forms_tags %} -->

{% block extrahead %}
<link rel="stylesheet" href="{% static 'Users/index.css' %}">
{% endblock extrahead %}

{% block content %}
    <div class="forms">
    <div class="forms-container">
        <form class='fm-pg' method="POST" action="" >
            {% csrf_token %}
            <h3 class='fm-header'>Register</h3>
            <div className='fm-form'>
                {{form.as_p}}
            </div>
            <button type="submit">Sign Up</button>
    </div>
    <div class="forms-container">
        <small class="text-muted">
            Already Have an Account?<a href="{% url 'Login' %}">Sign In</a>
        </small>
    </div>
    </div>
{% endblock content %}



{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}

Users/templates/Users/User.html
{% extends 'music-app/index.html' %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'Users/index.css' %}">
{% endblock %}
{% block content %}
    <div class="account">
    <div class="forms-container account">
        <h1 class="account-header">{{user}}'s Account</h1>
        <div class="account-details">
            <div class="account-img">
                <img src="{% static 'Users/account.png' %}" alt="Account img">
            </div>
            <div class="account-detail">
                <p><strong style="color: black;">Username:</strong> {{user.username}}</p>
                <p><strong style="color: black;">Mail:</strong> {{user.email}}</p>
            </div>
            


        </div>

    </div>
</div>
{% endblock content %}



{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}

music_app/templates/music-app/AboutPage.html
{% extends "music-app/index.html" %}
{% load static %}
{% block content %}
    <div class="about-page">
        <div class="">
            <h1 class="about-header">About Page</h1>
            <div class="desrcption">
                <p>1.<strong>New User:</strong>In order to view the music you have to Register first and login to the page.</p>
                <p>2.<strong>Existing User:</strong>
                    Existing User can Login to the portal and they can upload the music file in private,public,protected type.
                </p>
                Users can upload music files as public/private/protected.


                <p>3.<strong>Details:</strong>
                    Users can upload music files as public/private/protected.
                    <ul>
                        <li><p><strong>Public Music File:</strong> Visible to all the users</p></li>
                        <li><p><strong>Private Music File:</strong> Visible to the user who has uploaded it</p></li>
                        <li><p><strong>Protected Music File: </strong> Visible to users who have access to the file using email</p></li>
                            
                    </ul>
                </p>

                <p>
                   4.<strong>Protected Music File Details:</strong> When user uploads any music file as a protected music file, ask him/her to add multiple email addresses.
                            Check if the user with any mentioned email address is registered on the portal or not.
                            If there is a user with email in allowed emails list, then show him/her that music file.
                            When the user login, show him/her all the music files for which he/she has access on the homepage. (Music files that are uploaded by logged-in user, all public music files uploaded by other users, and protected files for which logged- in user has access)
                </p>

            </div>
        </div>
        
    </div>
{% endblock content %}


{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}

music_app/templates/music-app/HomePage.html
{% extends "music-app/index.html" %}
{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'music-app/music_playlist.css' %}">
{% endblock extrahead %}

{% block content %}
<!-- MAIN PAGES -->
    <div class="main-page">
        <h1 class="main-heading" style="text-align: center;">Music Sharing Portal</h1>
        <div class="main-user">
            <p>Welcome, {{ user.username }}</p>
            <div class="play-music">
                <audio id="audio">
                    <source src="" id="audioSource" type="audio/mpeg">
                </audio>
                <span class="audio-title" id="audioTitle">Title</span>
                
                <div class="player-middle-row">
                    <div class="player-middle-left">
                        <span  id="audioPlayPause"><i class="fa fa-play"></i></span>
                        <span  id="audioStop"><i class="fa fa-stop"></i></span>
                    </div>
                    <div class="player-middle-right">
                        <span id="duration">0:0</span>
                        <span id="durationUpdate">0:0</span>

                    </div>
                </div>
                <span class="audio-visibility" id="audioVisibility">visible</span>
            </div>
        </div>
<!-- MUSIC LISTING CODE -->
        <div class="main-music-lists">
            <!-- USER UPLOADS MUSIC FILES -->
                <div class="music-lists">
                    <h1 style="font-size: 18px;">User Uploads music files:</h1>
                    <div class="music-list-continer">
                    {% for User_file in User_upload_files %}
                        <a class="aTrigger" data-active="" data-audio=media/{{User_file.music_file}} > 
                        <div class="music-each">
                            <div class="music-detail">
                                <p class="title">{{User_file.title}}</p>
                                <p class="music-path">{{User_file.music_file}}</p>
                                <div class="music-upload-detail">
                                    <p class="music-uplloadedby">uploaded by <strong>{{User_file.uploaded_by}}</strong></p>
                                    <p class="music-visibility">{{User_file.get_visibility_display}}</p> 
                                </div>
                                
                            </div>
                            <p id="play-btn" class="play-btn"><i class="fa fa-play"></i></p>
                        </div>
                        </a>  
                    {% empty %}
                        <div>
                           <strong>No music files available</strong> 
                        </div>
                    {% endfor %}
                    </div>
                </div>
                    
                <!-- ALL USERS PUBLIC MUSIC FILES -->
                <div class="music-lists">
                    <h1 style="font-size: 18px;">All Public Music:</h1>
                    <div class="music-list-continer">
                    {% for public_file in public_files %}
                    <a class="aTrigger" data-active="" data-audio=media/{{public_file.music_file}} > 
                    <div class="music-each">
                        <div class="music-detail">
                            <p class="title">{{public_file.title}}</p>
                                <p class="music-path">{{public_file.music_file}}</p>
                            
                            <div class="music-upload-detail">
                                <p class="music-uplloadedby">uploaded by <strong>{{public_file.uploaded_by}}</strong></p>
                                <p class="music-visibility">{{public_file.get_visibility_display}}</p> 
                            </div>
                            
                        </div>
                        <p id="play-btn" class="play-btn"><i class="fa fa-play"></i></p>
                    </div>
                    </a>  
                    
                    {% empty %}
                        <div>
                            No public music files available
                        </div>
                    {% endfor %}
                    </div>
                </div>

                <!-- ALL USERS PROTECTED MUSIC FILES -->
                <div class="music-lists">
                    <h1>Protected Music Files:</h1>
                    <div class="music-list-continer">
                    {% for protected_file in protected_files %}
                    <a class="aTrigger" data-active="" data-audio=media/{{protected_file.music_file}} > 
                    <div class="music-each">
                        <div class="music-detail">
                            <p class="title">{{protected_file.title}}</p>
                            <p class="music-path">{{protected_file.music_file}}</p>
                            <div class="music-upload-detail">
                                <p class="music-uplloadedby">uploaded by <strong>{{protected_file.uploaded_by}}</strong></p>
                                <p class="music-visibility">{{protected_file.get_visibility_display}}</p> 
                            </div>
                            
                        </div>
                        <p id="play-btn" class="play-btn"><i class="fa fa-play"></i></p>
                    </div>
                    </a>  
                    
                    {% empty %}
                        <div>
                            No music files available
                        </div>
                    {% endfor %}
                    </div>
                </div>



        </div>
    
    
    </div>




{% endblock content %}


{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}

music_app/templates/music-app/UploadMusic.html
{% extends "music-app/index.html" %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'Users/index.css' %}">
{% endblock extrahead %}
{% block content %}
    <div class="forms">
    <div class="forms-container">
        <form class='fm-pg' method="POST" action="" enctype="multipart/form-data" >
            {% csrf_token %}
            <h3 class='fm-header'>Upload Music</h3>
            <div className='fm-form'>
                <div>
                    <label for="title">Title:</label>
                    <input type="text" name="title" id="title" required>
                </div>

                <div>
                    <label for="file">File:</label>
                    <input type="file" name="file" id="file" required>
                    <span>only .mp3 etc allowed</span>
                </div>

                <div>
                    <label for="visibility">Visisbility:</label>
                    <select name="visibility"  id="visibility" onchange="funVisbility()" required>
                        <option  value="public" selected>Public</option>
                        <option value="private">Private</option>
                        <option value="protected">Protected</option>

                    </select>

                    
                </div>
                <br/>
                <div class="access-emails"style="visibility: hidden;" >
                        <label for="allowed_emails">Allowed Emails(Comma-separated):</label>
                        <input type="text" name="allowed_emails" id="allowed_emails">
                </div>

            </div>
            <button type="submit">Upload</button>
    </div>
    
    </div>
{% endblock content %}


{% block extra_js_top %}
<script src="{% static 'index.js' %}" type="javascript"></script>
{% endblock %}